/**
 * Route Index - Auto-generated by refactor_tool.js
 * Loads all modular route files and mounts them on the Express app
 */
module.exports = function mountRoutes(app) {

    // auth (4 routes) — mounted at /api/auth
    app.use('/api/auth', require('./auth.js'));

    // dashboard (4 routes)
    app.use('/', require('./dashboard.routes.js'));
    // patients (14 routes)
    app.use('/', require('./patients.routes.js'));
    // appointments (10 routes)
    app.use('/', require('./appointments.routes.js'));
    // lab (15 routes)
    app.use('/', require('./lab.routes.js'));
    // radiology (5 routes)
    app.use('/', require('./radiology.routes.js'));
    // pharmacy (25 routes)
    app.use('/', require('./pharmacy.routes.js'));
    // nursing (13 routes)
    app.use('/', require('./nursing.routes.js'));
    // hr (8 routes)
    app.use('/', require('./hr.routes.js'));
    // finance (23 routes)
    app.use('/', require('./finance.routes.js'));
    // insurance (8 routes)
    app.use('/', require('./insurance.routes.js'));
    // inventory (12 routes)
    app.use('/', require('./inventory.routes.js'));
    // surgery (21 routes)
    app.use('/', require('./surgery.routes.js'));
    // blood_bank (11 routes)
    app.use('/', require('./blood_bank.routes.js'));
    // emergency (6 routes)
    app.use('/', require('./emergency.routes.js'));
    // inpatient (9 routes)
    app.use('/', require('./inpatient.routes.js'));
    // icu (9 routes)
    app.use('/', require('./icu.routes.js'));
    // settings (9 routes)
    app.use('/', require('./settings.routes.js'));
    // messaging (7 routes)
    app.use('/', require('./messaging.routes.js'));
    // reports (29 routes)
    app.use('/', require('./reports.routes.js'));
    // consent (11 routes)
    app.use('/', require('./consent.routes.js'));
    // specialty consents
    app.use('/', require('./specialty_consent.routes.js'));
    // catalog (7 routes)
    app.use('/', require('./catalog.routes.js'));
    // cssd (10 routes)
    app.use('/', require('./cssd.routes.js'));
    // dietary (7 routes)
    app.use('/', require('./dietary.routes.js'));
    // infection (10 routes)
    app.use('/', require('./infection.routes.js'));
    // quality (8 routes)
    app.use('/', require('./quality.routes.js'));
    // maintenance (11 routes)
    app.use('/', require('./maintenance.routes.js'));
    // transport (3 routes)
    app.use('/', require('./transport.routes.js'));
    // portal (4 routes)
    app.use('/', require('./portal.routes.js'));
    // zatca (8 routes)
    app.use('/', require('./zatca.routes.js'));
    // telemedicine (3 routes)
    app.use('/', require('./telemedicine.routes.js'));
    // pathology (5 routes)
    app.use('/', require('./pathology.routes.js'));
    // social_work (3 routes)
    app.use('/', require('./social_work.routes.js'));
    // mortuary (3 routes)
    app.use('/', require('./mortuary.routes.js'));
    // cme (6 routes)
    app.use('/', require('./cme.routes.js'));
    // rehab (7 routes)
    app.use('/', require('./rehab.routes.js'));
    // medical_records (7 routes)
    app.use('/', require('./medical_records.routes.js'));
    // obgyn (12 routes)
    app.use('/', require('./obgyn.routes.js'));
    // referral (6 routes)
    app.use('/', require('./referral.routes.js'));
    // audit (2 routes)
    app.use('/', require('./audit.routes.js'));
    // notifications (2 routes)
    app.use('/', require('./notifications.routes.js'));
    // waiting (4 routes)
    app.use('/', require('./waiting.routes.js'));
    // forms (3 routes)
    app.use('/', require('./forms.routes.js'));
    // doctor (3 routes)
    app.use('/', require('./doctor.routes.js'));

    // 🇸🇦 Saudi Compliance (19 routes — NPHIES, Wasfaty, ZATCA P2, Yaqeen)
    app.use('/api/compliance', require('./compliance.routes.js'));

    // 🩺 Clinical Workflows (22 routes — CPOE, Drug Checks, Flowsheets, Alerts)
    app.use('/api/clinical', require('./clinical.routes.js'));

    // 💡 Smart Suggestions APIs (Diagnoses, Labs, Radiology based on Specialty)
    app.use('/', require('./smart_suggestions.routes.js'));

    console.log('  📦 Modular routes loaded: 46 modules, 424 routes');
};